name = "NatureInspiredOptimization"
uuid = "8027fc3b-3b57-42c8-bbd2-75f0210cbcdc"
authors = ["Eric S Fraga <e.fraga@ucl.ac.uk>"]
version = "0.8.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
